### ISSUE TITLE
Can't update to Xcode 14.2 

### ISSUE THREAD

**Issue by SerggioC** [RobotsAndPencils/XcodesApp#345] opened 2023-01-02 14:29 UTC
The operation couldn’t be completed. (ProcessExecutionError(process: <NSConcreteTask: 0x600000008320>, standardOutput: "", standardError: ""))
![Captura de ecrã 2023-01-02, às 14 26 15](https://user-images.githubusercontent.com/21109275/210244695-0645c783-d37c-44b1-9833-c7f186204d9b.png)

What could be the issue?

Thank you.

**Comment by leon-wolf** [comment] 2023-01-03 12:58
Duplicate of [this](https://github.com/RobotsAndPencils/XcodesApp/issues/338)

Possible Solution: [this](https://github.com/RobotsAndPencils/XcodesApp/issues/316#issuecomment-1292103479)

Please use the provided template when reporting bugs. It helps a lot, when trying to troubleshoot your problems. :)

**Comment by MattKiazyk** [comment] 2023-01-04 04:04
Hey @SerggioC - please follow the links posted above for your solution - thanks!

**Closed by MattKiazyk** 2023-01-04 04:04 UTC

**Comment by SerggioC** [comment] 2023-01-06 12:50
Thanks, but it didn't work. The folder is empty but the error still occurs.

**Comment by SerggioC** [comment] 2023-01-06 14:00
Solved after copying the app to the Applications folder.
