### ISSUE TITLE
Auto download

### ISSUE THREAD

**Issue by jacobwhite** [RobotsAndPencils/XcodesApp#108] opened 2021-02-18 08:56 UTC
I hate waiting for Xcode to download, would be super cool if the latest beta could download and extract itself as soon as it’s available, so it’s there ready and waiting for me when I need it.

**Comment by interstateone** [comment] 2021-02-18 14:25
Hey @jacobwhite, this is a duplicate of #99 right?

**Comment by jacobwhite** [comment] 2021-02-18 16:02
Oh yeah! I thought I’d made this request before but didn’t see it when I looked. Sorry about that lol

**Closed** 2021-02-18 16:14 UTC
Labels: enhancement

**Comment by MattKiazyk** [comment] 2021-03-11 01:32
Included in 1.0.5 - let us know if you see any issues.
